name: Check for Updates and Build Docker Image

on:
  schedule:
    - cron: '0 0 * * MON' # Runs at 00:00 UTC every Monday
  workflow_dispatch: # Allows manual triggering of the workflow

env:
  REGISTRY: ghcr.io
  REGISTRY_PW: ${{ secrets.GHCR_TOKEN }}
  IMAGE_NAME: inso-container
  ALPINE_URL: https://registry.hub.docker.com/v2/repositories/library/alpine/tags/latest
  INSO_URL: https://api.github.com/repos/Kong/insomnia/releases/latest

defaults:
  run:
    shell: bash

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ env.REGISTRY_PW }}

      - name: Check for new Alpine image
        id: check_alpine
        run: |
          latest_alpine=$(curl -s ${{ env.ALPINE_URL }} | jq -r '.last_updated')
          echo "latest_alpine=$latest_alpine" >> $GITHUB_ENV

      - name: Check for new Inso release
        id: check_inso
        run: |
          latest_inso=$(curl -s ${{ env.INSO_URL }})
          inso_version=$(echo $latest_inso | jq -r '.tag_name')
          inso_published_at=$(echo $latest_inso | jq -r '.published_at')
          inso_download_url=$(echo $latest_inso | jq -r '.assets[] | select(.name | contains("inso") and contains(".tar.xz")) | .browser_download_url')
          echo "inso_version=${inso_version#*@}" >> $GITHUB_ENV
          echo "inso_published_at=$inso_published_at" >> $GITHUB_ENV
          echo "inso_download_url=$inso_download_url" >> $GITHUB_ENV

      - name: Compare timestamps
        id: compare
        run: |
          alpine_timestamp=$(date -d "$latest_alpine" +%s)
          inso_timestamp=$(date -d "$latest_inso" +%s)
          current_timestamp=$(date +%s)
          alpine_diff=$(( (current_timestamp - alpine_timestamp) / 86400 ))
          inso_diff=$(( (current_timestamp - inso_timestamp) / 86400 ))
          echo "alpine_diff=$alpine_diff" >> $GITHUB_ENV
          echo "inso_diff=$inso_diff" >> $GITHUB_ENV

      - name: Build and push Docker image
        if: steps.compare.outputs.alpine_diff < 7 || steps.compare.outputs.inso_diff < 7
        run: |
          docker build -t ${{ env.IMAGE_NAME }} --build-arg INSO_DOWNLOAD_URL=${{ env.inso_download_url }} .
          docker tag ${{ env.IMAGE_NAME }} ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ github.repository }}/${{ env.IMAGE_NAME }}:latest
